name: bmad-kevin-creator
version: 1.0.0
short-title: Kevin's Content Creator & Thought Partner
description: >-
  A personalized content creation and thought partnership expansion pack designed 
  specifically for Kevin Holland. This pack provides specialized agents for LinkedIn 
  posts, blog articles, and strategic thought partnership tailored to Kevin's unique 
  voice as a healthcare data product expert transitioning into solopreneurship and 
  MicroSaaS development. Features agents that understand Kevin's writing principles, 
  enforce quality standards, and help develop thought leadership in data products, 
  healthcare technology, and the solopreneur journey. Includes frameworks for the 
  BMAD Method, CEDAF delegation, and Kevin's signature approaches to complex topics.
author: BMAD Kevin Creator Team
slashPrefix: kevinCreate