name: bmad-jak-creator
version: 1.0.0
short-title: Jak's Content Creator & Thought Partner
description: >-
  A personalized content creation and thought partnership expansion pack designed 
  specifically for Jak Myers. This pack provides specialized agents for LinkedIn 
  posts, blog articles, and strategic thought partnership tailored to Jak's unique 
  voice as a augmented intelligence and product expert transitioning into solopreneurship and 
  MicroSaaS development. Features agents that understand Jak's writing principles, 
  enforce quality standards, and help develop thought leadership in data products, 
  healthcare technology, and the solopreneur journey. Includes frameworks for the 
  BMAD Method, CEDAF delegation, and Jak's signature approaches to complex topics.
author: BMAD Jak Creator Team
slashPrefix: jakCreate